### ISSUE TITLE
Xcode Cloud compatibility

### ISSUE THREAD

**Issue by DanArcari** [axmolengine/axmol#1000]
There seems to be a chicken-and-egg setup process with axmol-based games that prevents usage with Xcode Cloud. A game which builds successfully in Xcode locally, will (IME, anyway) fail during a cloud build b/c there are numerous references to local paths that were generated as part of the original `cmake` process. In my case, this is a `"failed to read asset tags" The file /Users/me/projects/<game_name> doesn't exist."` error. (path made up, but you get the idea)

I believe this is due to all the generated project content containing references to wherever the project is located on local disk, rather than relative references. 

This can be avoided by checking-in the entire axmol-dev directory (big!) and re-running the `cmake` step as part of the build process. On most CI systems, this is probably OK (although I haven't tested yet), but does not work with Xcode Cloud, because Xcode Cloud links the cloud build with project-specific identifiers that change every time the .xcodeproj file is regenerated. You have to setup cloud builds after the project exists, and can't keep changing the project file.

What's needed is a way to generate the project so that there are no absolute references to the original local disk location. Everything needs to be relative to either `AX_ROOT` or other environment variables specified for the build. This would not only enable Xcode Cloud, which is a cheaper and simpler solution than other CI setups, but would also clean up the generated content to make the entire source code bundle more portable.

If this is _already_ possible somehow and I'm just ignorant of how to do so, I'd appreciate any pointers.

**Comment by rh101** [comment]
It seems that there are several issues here:

1 - For your use-case, you would need a copy of the axmol engine source within the project folder, the same way cocos2d-x handles it.  The actual size of the folder is around 500MB.  The _tests_ and _templates_ should not be copied across.  I'm not sure if the python script code was removed (since the `axmol` script was adapted from cocos2d-x), but I feel that this should be re-enabled to give the developer an option to have the engine as part of the project source tree.  The AX_ROOT would then just be changed to point to the folder, whether via the environment variable, or directly in the project root `CMakeLists.txt` file (more info [here](https://github.com/axmolengine/axmol/discussions/968#discussioncomment-4453785)).

A command line switch to the 'axmol' project generator should be added to allow the developer to select whether or not to copy the relevant engine source to the game project (say to a folder named `axmol`), and it would simply change the AX_ROOT in the `CMakeLists.txt` to be:
`set(_AX_ROOT ${CMAKE_CURRENT_SOURCE_DIR}/axmol)`

I'm not certain if fixing this will help with the absolute paths, since it's a cmake issue.  More info [here](https://gitlab.kitware.com/cmake/community/-/wikis/FAQ#why-does-cmake-use-full-paths-or-can-i-copy-my-build-tree).

2 - CMake support for deterministic identifiers when the Xcode project is generated may help with the Xcode Cloud build, but from what I've read on this, it hasn't been added to it yet (some info [here](https://discourse.cmake.org/t/deterministic-ids-in-the-xcode-generator-to-avoid-unnecessary-rebuilds/1870) that may be relevant to this issue). The only way around this may be to generate the project files and commit them along with the source code (which I assume is what you're already doing).

Hopefully someone else may have ideas on how to work-around these issues with cmake and Xcode Cloud.

**Comment by DanArcari** [comment]
@rh101 Thanks for your comments. Copying the entire axmol directory into the project directory works for compilation on a standalone system, but still requires re-running `cmake`, which leads back to the Xcode Cloud incompatibility issue.

If the cmake issues are effectively a blocker (it seems so, but I'm definitely not an expert there), then it seems cmake should be used only for initial project generation, but not as part of the build process thereafter? Or perhaps cmake isn't needed at all? There's a lot of setup here from python -> cmake -> xcode. Maybe things could be simplified?

It's conceivable that an xcodeproj could be created, from scratch at least, that would build the game and all the dependencies without needing to run cmake scripts at all. Perhaps that should be an option? 

Would using entirely prebuilt libraries help here? Is that possible with the current state of axmol?

**Comment by rh101** [comment]
Just to clarify, the issues with Xcode Cloud have nothing to do with the current state of axmol, or axmol in general.  

> If the cmake issues are effectively a blocker (it seems so, but I'm definitely not an expert there), then it seems cmake should be used only for initial project generation, but not as part of the build process thereafter? Or perhaps cmake isn't needed at all?

You could try this, but you would have to maintain the project files yourself.  You could try to manually create a new Xcode project, and add all the relevant code to it, or alternatively it may be easier way would be to generate the Xcode project via CMake, and then edit that to your needs.

> There's a lot of setup here from python -> cmake -> xcode. Maybe things could be simplified?

Python is only used to generate the initial project, not required thereafter.  CMake is used to simplify everything, since there is no longer any need to maintain project files for different platforms, as all the work is done via CMake (everything goes in `CMakeLists.txt`).  I'm not sure it could get any simpler than that.

> Would using entirely prebuilt libraries help here? Is that possible with the current state of axmol?

I'm not entirely sure if that would solve the issues you're having, but you could always try it out.

**Comment by danarcari** [comment]
For the benefit of anyone else that wants to build on an agnostic system, I was able to get an axmol project to build on XCodeCloud by doing the following:

* In Xcode, go to Scheme -> Edit Scheme... and note the target used for the Build action. You'll have to recreate this later (it's just one click really, but if you're not familiar with Xcode projects might be confusing). Take a screenshot maybe.
* Open the `project.pbxproj` file inside `build/<game>.xcodeproj`, then replace all occurrences of hard-coded paths referring to your local file system with a relative reference, I used $(PROJECT_DIR), in quotes, so `"$(PROJECT_DIR)/path/to/whatever/file";` There will be _a lot_ of these, so be patient. I made some mistakes doing this which invalidated the project file, fixing these was _way_ easier using [Kin](https://github.com/Serchinastico/Kin).
* When done, reopen the project in XCode to make sure it at least opens. Other things may look weird though.
* Then, back in the pbxproj file, make sure that `projectDirPath = ""` This will probably have a hard-coded value when first generated by axmol, you want an empty string.
* This will likely mess up your scheme and target settings, so in Xcode, go to Scheme -> Edit Scheme... and make sure that the scheme for the actual game looks the same as in step 1 before changing stuff.
* At this point, unless your path changes in the pbxproj file were wrong, the game should build and run locally (incl. simulator and attached devices, if you have these configured in Apple Developer account).
* In order to get building on XcodeCloud, I also had to delete the script that was re-running Cmake stuff on every build, since all of the generated Cmake files contain hard-coded references to your local filesystem, which makes building axmol games on a CI system impossible (AFAICT). Open the ZERO_CHECK target that's part of the project, go to Build Phases, select the Generate CMake Files/ZERO_CHECK step, and delete the script content (save it off somewhere). You can possibly delete this whole target, but I went for the minimal number of changes.
* Finally, I had to delete and redo the game's launch storyboard and icon stuff b/c I think some of the path changes messed these up. Not sure this will happen for others, and you'll get errors on XcodeCloud that will indicate problems here anyway.

With the above done, I was able to get a game fully building and uploading into AppStoreConnect. Hope this helps anyone else looking to do the same!

Note: Changing the Cmake stuff might mess up builds for the library targets that included in the project, this has not affected anything for me, but maybe if you're making active changes to them something won't work. Modifying all the Cmake stuff to have relative paths, or ripping out Cmake entirely is beyond my expertise though.

All of this also works on GitHub Actions, you just have to have a workflow file that runs `xcodebuild ...`, whereas XcodeCloud knows what to do by default.

**Comment by rh101** [comment]
> * In order to get building on XcodeCloud, I also had to delete the script that was re-running Cmake stuff on every build, since all of the generated Cmake files contain hard-coded references to your local filesystem, which makes building axmol games on a CI system impossible (AFAICT). Open the ZERO_CHECK target that's part of the project, go to Build Phases, select the Generate CMake Files/ZERO_CHECK step, and delete the script content (save it off somewhere). You can possibly delete this whole target, but I went for the minimal number of changes.

Don't the current [workflows](https://github.com/axmolengine/axmol/blob/dev/.github/workflows/build.yml) mean that Axmol does build on a CI system?  Every PR submitted is automatically built to ensure there are no build errors using the CI on github, so I'm surprised that XcodeCloud wouldn't support a similar method.

The issue is perhaps not with Axmol or Cmake, but seems to be with the fact that the code is checked out of source control on a local system, build files created with cmake, then uploaded somewhere (Xcodecloud?) and built.  Is there no way to have XcodeCloud clone the relevant repo, then create the build files, then build, like what github does at the moment with its CI system?

**Comment by danarcari** [comment]
> > * In order to get building on XcodeCloud, I also had to delete the script that was re-running Cmake stuff on every build, since all of the generated Cmake files contain hard-coded references to your local filesystem, which makes building axmol games on a CI system impossible (AFAICT). Open the ZERO_CHECK target that's part of the project, go to Build Phases, select the Generate CMake Files/ZERO_CHECK step, and delete the script content (save it off somewhere). You can possibly delete this whole target, but I went for the minimal number of changes.
> 
> Don't the current [workflows](https://github.com/axmolengine/axmol/blob/dev/.github/workflows/build.yml) mean that Axmol does build on a CI system? Every PR submitted is automatically built to ensure there are no build errors using the CI on github, so I'm surprised that XcodeCloud wouldn't support a similar method.
> 
> The issue is perhaps not with Axmol or Cmake, but seems to be with the fact that the code is checked out of source control on a local system, build files created with cmake, then uploaded somewhere (Xcodecloud?) and built. Is there no way to have XcodeCloud clone the relevant repo, then create the build files, then build, like what github does at the moment with its CI system?

Those are builds for axmol itself, I'm referring to having an axmol-powered _game_ building on a CI system, which is what my steps allow for (although I likely missed something).

**Comment by rh101** [comment]
> Those are builds for axmol itself, I'm referring to having an axmol-powered _game_ building on a CI system, which is what my steps allow for (although I likely missed something).

The automated builds don't build just Axmol, they build the existing test projects, which are "axmol-powered", and no different than any project that would be created via the "axmol new" command.  If you want to see more, just check any pull request, and click on the "Checks" tab, then the "ios" job. Perhaps something there can point you in the right direction.

**Comment by smilediver** [comment]
I have no idea how Xcode Cloud works, so might be wrong... but giving it a glance it appears that it can only build Xcode projects, so you can't generate one in the cloud. Probably the only viable choice is to maintain a separate Xcode project for Xcode Cloud.

**Comment by rh101** [comment]
> I have no idea how Xcode Cloud works, so might be wrong... but giving it a glance it appears that it can only build Xcode projects, so you can't generate one in the cloud. Probably the only viable choice is to maintain a separate Xcode project for Xcode Cloud.

There seems to be some misunderstanding.  Xcode or Xcode cloud will build an Xcode project, but what I've been trying to point out is that the CI system clones the repository, runs the relevant command (cmake or `axmol build ...`) which generates the Xcode project, and then that project is built.  You should not have to maintain a separate Xcode project.  

I am not familiar with Xcode Cloud, but given it's meant to be a CI service, then it would be strange not to support automatically handling all the aforementioned steps.   If it does, then you will be making your life a lot easier.

**Comment by rh101** [comment]
> I have no idea how Xcode Cloud works, so might be wrong... but giving it a glance it appears that it can only build Xcode projects, so you can't generate one in the cloud. Probably the only viable choice is to maintain a separate Xcode project for Xcode Cloud.

~~There seems to be some misunderstanding.~~ Sorry, I misread your post. I am not familiar with Xcode Cloud either, but given it's meant to be a CI service, then it would be strange not to support automatically handling the typical workflow of other CI systems (clone repo/run command to generate project/build). If it does, then it would make things a lot easier for anyone that uses it.

**Comment by smilediver** [comment]
> CI system should support cloning a repository, running the relevant command (cmake or `axmol build ...`)

That's what a normal CI system does, but this is Apple. :) As I understand Xcode Cloud (and I might be wrong), you supply a repo, you point to an Xcode project, and tell what to build from that project. There's no way to run custom commands (maybe apart from those commands being run from inside the Xcode project).

Maybe it would be possible to setup a different Xcode project that would run `axmol build`... but that's a BIG maybe.
