### ISSUE TITLE
TMX sprite disappears 

### ISSUE THREAD

**Issue by Joilnen** [axmolengine/axmol#1106]
- axmol version:fe4b7622660ebe28832d3feca9537c962a6202be
- devices test on: linux x86_64 
Steps to Reproduce:
auto map = TMXTiledMap::create("map.tmx");
auto sprite = map->getLayer("Layer_0")->getTile(Vec2(2, 18);

sprite is not null but it disappear from my scene after lasts commits in FastTMX code, behaving different from old code.

**Comment by rh101** [comment]
Is this reproducible with the cpp-tests project, or is it specific to your `map.tmx` file and resources? If it's not reproducible with cpp-tests, then it's best to provide a TMX file and associated resources that does reproduce the issue.

**Comment by DelinWorks** [comment]
@Joilnen if you coulde give us the reproducible project and tmx map that would help a lot in fixing this issue!

**Comment by Joilnen** [comment]
This figure is showed in bc0b7da754c984f21a2ed82f22c3167a05435677 
but now after 4c2856998abfc9a597994e96d1373982e27cd801 it shows me only a black screen, noticed the sprite was flipped in tiled

![BugFlip](https://user-images.githubusercontent.com/134140/224512420-9eb153c6-92b4-4339-bd3d-45095fd9c6eb.png)
[BugFlip.zip](https://github.com/axmolengine/axmol/files/10949497/BugFlip.zip)

**Comment by rh101** [comment]
Out of curiosity I tested the supplied code, and noticed that this line in 'FirstScene.cpp' is causing the issue, but I don't know why:

`front_map->getLayer("inalayer")->getTileAt(Vec2(2, 18));`

If you comment it out, then the tile appears and animates correctly (when compared to what is in Tiled).

Also, just for future reference, when providing test code, it's best to reduce it to the least possible amount of code to reproduce the issue.  The code provided contains a `ParallaxNode` that has been applied to the tiled map, but has nothing to do with the issue, and just serves to complicate things.

**Comment by rh101** [comment]
It looks like the tile flags aren't being stored when a Sprite is created for a tile, and also the incorrect coordinates are being passed every time an existing sprite is being used to draw a tile on the screen.

**Comment by Joilnen** [comment]
after I do getTileAt the sprite create is not flipped there is a way to me check this flag from tmx in axmol ?

**Comment by rh101** [comment]
@Joilnen What do you mean? With the current implementation the tile sprite in Axmol looks exactly the same as what is shown in the Tiled app.

What exactly is wrong with it?

**Comment by Joilnen** [comment]
I can get flipped flag doing getTileGIDAt right ?

**Comment by rh101** [comment]
Show an example of what you mean. A picture is worth a thousand words, so take a screenshot of the tile in your app, and the same tile from Tiled, and post them here.  Label each one as "Expected" (what you see in Tiled) and "Actual" (what you see in your app).

**Comment by Joilnen** [comment]
yes I supposed the last changes in TMX support code would gives me a flipped sprite already, but it is ok thanks your patch works fine.

**Comment by rh101** [comment]
I'm sorry, I don't understand what you keep mentioning the flipped sprite, or what the issue is that you're having.

The current code in axmol displays the tile **exactly** how it is displayed in Tiled, and that includes rotations etc. 

If you're comparing Axmol to Cocos2d-x and you're seeing different output from both, then what you're stating would make more sense, because Cocos2d-x has a bug, and that bug was fixed in Axmol (by @DelinWorks).

**Comment by Joilnen** [comment]
Here you can see that Flipped sprites only works when animated after you make getTileAt, this is what I mean
[BugFlip.zip](https://github.com/axmolengine/axmol/files/10951651/BugFlip.zip)

**Comment by DelinWorks** [comment]
@rh101 I think what @Joilnen meant to say is that when you try to take a tile from a tmx map and render it as a sprite, the rotation/flipped flags should apply to that sprite and rotate/flip said sprite accordingly, weirdly enough the sprite is rendered based on tiled flags and is shown rotated/flipped but only and only if the sprite is animated. Sorry @Joilnen if I misinterpreted something.

**Comment by rh101** [comment]
@Joilnen Thank you for providing the new test, because now the issue is clear.

Expected (from Tiled) is this:
![image](https://user-images.githubusercontent.com/8603230/224579923-dc557b43-c330-4425-b338-b19d8ad4c1cf.png)

Actual output from Axmol:
![image](https://user-images.githubusercontent.com/8603230/224579934-fb4e750a-db67-4942-941d-74613bc1fd1c.png)

That should not be happening, and points at a completely separate problem, so it's best you create a new separate issue entry for it.

**Comment by rh101** [comment]
It's now displaying correctly with the change in #1114 

![image](https://user-images.githubusercontent.com/8603230/224580848-e1e0fa39-806c-4fcf-a8f2-88fb5796c2c5.png)

**Comment by rh101** [comment]
Also, note that calling `getTileAt()` for an animating tile will give you the sprite with the settings of the current animation frame being displayed, since the same sprite can be used for multiple frames.  `TMXTileAnimTask::setCurrFrame()` which calls `FastTMXLayer::setTileGID`, and that in turn changes the current texture coordinates and orientation of the sprite based on the current tile flags.
