### ISSUE TITLE
Live2d demo crash

### ISSUE THREAD

**Issue by RGAA-Software** [axmolengine/axmol#1403]
- axmol version: 2.1
- devices test on: Windows10

1. I known the reason of the crash is mismatched GLSL version.
![20231024235324](https://github.com/axmolengine/axmol/assets/122289026/018bc74f-091e-43ee-9cac-554afaafccde)

2. After modified the glsl at here(the screenshot is origin code, I've modified ,such as: attribute -> in; gl_FragColor -> out fragColor...):
![20231024235845](https://github.com/axmolengine/axmol/assets/122289026/cdd1b61e-6be6-4174-9147-8301843f74eb)

I still get the crash at here:

![20231024235400](https://github.com/axmolengine/axmol/assets/122289026/3942e9f0-ce7a-4155-8d06-28df609687cb)

Any idea ? Thank you very much!

**Comment by rh101** [comment]
~~The screenshots you provided show that the shader code is embedded into your CPP code, and if that is the case, then that is most likely the problem.~~ EDIT: Sorry, I misread, and just realised that it's the Live2D test that you're referring to.  The issue is the same though, and it needs to be updated in order for it to work.  You can do that yourself and submit a PR if you wish.

Axmol 2.0 requires that the shader source code is in separate files, as they are processed during build time to generate the correct shaders for different platforms.

Refer to #1279 for all the information you require in order to get it working.  The information on that page should perhaps be placed somewhere that is more accessible, so that is something that should be addressed.

Note, the only issue I can see is this part of the shader:

```
#if defined(AX_USE_METAL)
        "    gl_Position = vec4(position.x, -position.y, position.z, 1.0);"
#else
        "    gl_Position = vec4(position, 1.0);"
#endif
```

~~I'm not sure if it is possible to add conditionals like that.  @halx99 Is that possible with the axslc implementation? If not, is there a way to have 2 different source files and be selective about which one the axslc processes for a given platform?~~ Nevermind, I just noticed that it can be done:

```
#if defined(METAL)
#endif 
```

**Comment by rh101** [comment]
No need to do anything.  A PR will be up soon with the updates to get Live2D working with Axmol 2.x.

It's working with Axmol 2.x now:
![image](https://github.com/axmolengine/axmol/assets/8603230/0215d046-cd11-4e2f-b792-9c3882f988b5)

**Comment by RGAA-Software** [comment]
**Thank you very much!**
