### ISSUE TITLE
axmol ios project with CocoaPods

### ISSUE THREAD

**Issue by Dazlonar** [axmolengine/axmol#1720]
Hello! 
Our iOS project uses [CocoaPods](https://cocoapods.org/) as a dependency management tool. Now I'm trying to migrate our cocos2dx project to axmol, but I'm getting an error during the build with pods.
To rule out that the problem might be in our project, I created a clean axmol project and tried to integrate the pods, but I got the same error:
```
Framework 'Pods_axmoltest' not found
Linker command failed with exit code 1 (use -v to see invocation)
```
I understand that this problem does not directly relate to the axmol engine, but there is probably a problem in the project settings that is causing this to happen. Perhaps someone has an idea why this could be.

- axmol version: 2.1.2
- developing environments
   - Xcode version: 15.2
   - CocoaPods: 1.15.2

Steps to Reproduce:

1. Create a new axmol project with command: `axmol new axmoltest -l cpp -p com.axmol.test -d <your_proj_dir>`
2. Generate XCode proj: `axmol build -p ios -a arm64 -c`
3. [Install CocoaPods](https://guides.cocoapods.org/using/getting-started.html) if needed.
4. Create Podfile for example I am use this: 
```
platform :ios, '12.0'

use_frameworks!
use_modular_headers!

target 'axmoltest' do
  pod 'AppsFlyerFramework'
end
```
5. Install pods dependency: `pod install --repo-update`
6. Open workspace: `axmoltest.xcworkspace`
7. Choose correct target & Run build

**Comment by rh101** [comment]
@Dazlonar Out of curiosity, which version of Cocos2d-x are you migrating from?

**Comment by rh101** [comment]
Just did a test using the steps you provided.  `Pods_axmoltest.framework` does exist, although it is located in a temporary folder (xcode places it there):

`/Users/[user_id]/Library/Developer/Xcode/DerivedData/axmoltest-[somerandomletters]/Build/Products/Debug-iphoneos/Pods_axmoltest.framework`

You can see the location if you click on "Pods_axmoltest" under the Frameworks branch within the Xcode project.

Build it now resulted in the same error: `Framework 'Pods_axmoltest' not found`

So, in order to see if the paths are the issue, I added this to the `CMakeLists.txt`:
`set(CMAKE_XCODE_ATTRIBUTE_FRAMEWORK_SEARCH_PATHS "/Users/[user_id]/Library/Developer/Xcode/DerivedData/axmoltest-[somerandomletters]/Build/Products/Debug-iphoneos/")`

Re-generate the xcode project `axmol build -p ios -a arm64 -c`

Re-run `pod install --repo-update`

Open `axmoltest.xcworkspace`, and re-built.  It built successfully.

So, the search path may be the issue.  What I'm not entirely sure about is what you would need to set `CMAKE_XCODE_ATTRIBUTE_FRAMEWORK_SEARCH_PATHS` to in order for it to work with any temporary folder that is generated.
