### ISSUE TITLE
Build time extremely long.

### ISSUE THREAD

**Issue by asnagni** [axmolengine/axmol#1793]
Hi guys,
   We just migrated to Axmol from cocos2d-x 3.17.2. We noticed an issue with the build time. When we modify a simple file, at each time everything will be rebuild (no matter what). For us, that’s about 8 minutes looking at the screen for any simple change in a single file. That was not happening with cocos2d-x. So we are wondering that maybe we may have miss something! Perhaps there is a configuration flag with Axmol to setup and speed up the process and avoid rebuilding everything each time? Thank you for helping.

Stay safe

- axmol version: 2.1.2
- devices test on: iPhone 11, 12, 13, 14
- developing environments
   - NDK version: N/A
   - Xcode version:  N/A
   - Visual Studio: 
      - VS version:  N/A
      - MSVC version:  N/A
      - Windows SDK version:  N/A
   - cmake version: 3.29.0
Steps to Reproduce:

1. Create a project with Axmol
2. Add your files
3. Make tiny modifications in one file
4. Build

**Comment by rh101** [comment]
> * devices test on: iPhone 11, 12, 13, 14
> 
> * developing environments
>   
>   * NDK version: N/A
>   * Xcode version:  N/A

Judging by the devices listed, you're working on a Mac, yet you've set "Xcode version" to "N/A".  It's useful information to have, so which version of Xcode are you using? 

Also, some context would be helpful regarding the build time of 8 minutes.  During the build process, what do you see happening?  Is it re-compiling all the source code again, and if so, which source code? The engine source? Your project source?  What else is the build process doing that causes it to take such a long time?

I've personally noticed that it does do a full rebuild of the engine source code (with no `CMakeLists.txt` changes), which only happens when using Xcode.  It doesn't happen in Visual Studio and Android Studio, so it's something specific to Xcode projects.

**Comment by asnagni** [comment]
Fixed.

**Comment by asnagni** [comment]
Fixed using ccache. Would like to share the solution that I have.

**Comment by halx99** [comment]
i think you can share to discuss or wiki pages
