### ISSUE TITLE
Android: bug in getSafeAreaRect calculations

### ISSUE THREAD

**Issue by crazyhappygame** [axmolengine/axmol#1876]
- axmol version: 2.1.2
- devices test on: Motorolla g54, Xiaomi Pro 12
- developing environments
   - NDK version: r23c
   - Xcode version: 14.2+
   - Visual Studio: 
      - VS version: 2022 (17.9+)
      - MSVC version: 19.39+
      - Windows SDK version: 10.0.22621.0+
   - cmake version: 
Steps to Reproduce:

1. Draw ```auto safeAreaRect = _director->getSafeAreaRect();```
2. Bug: safeAreaRect does not take into account corners at the bottom of screen. 

Please check screenshots below. Blue rectangle it is safeAreaRect. For Android devices with rounded corners blue is not drawn properly. 

 Android incorrect: moto G54 (the same issue on other Android devices with rounded corners)
![WhatsApp Image 2024-05-02 at 22 02 29](https://github.com/axmolengine/axmol/assets/13263288/e11a34e5-47fd-4f6d-87c7-d8d7570f7db5)

IPhone correct: iPhone Max Pro 15
![WhatsApp Image 2024-05-02 at 21 58 32](https://github.com/axmolengine/axmol/assets/13263288/425ae6aa-8ca5-4e50-8c43-5229eb1c46ca)

**Comment by rh101** [comment]
Have you checked the `Rect GLViewImpl::getSafeAreaRect()` method in `GLViewImpl-android.cpp` when running on a device with rounded corners to see what is going on in there?  ~~Check if this line is returning `true`:
`bool isScreenRound = JniHelper::callStaticBooleanMethod("org/axmol/lib/AxmolEngine", "isScreenRound");`~~ Never mind, this is only for wearable devices.

**Comment by rh101** [comment]
@crazyhappygame I just had a look at this, and on creating a new project, and displaying this on an Android device with rounded corners, and the result seems correct:
![image](https://github.com/axmolengine/axmol/assets/8603230/504a8b29-8707-4de0-910b-f533a9b1c9ba)

There is no information in your initial post regarding how you set up the resolution policy, or any sample code, so there is nothing to go off in order to reproduce the issue quickly.  The above screenshot was taken with a the resolution policy set to `ResolutionPolicy::SHOW_ALL`.

**Comment by rh101** [comment]
When using `ResolutionPolicy::EXACT_FIT`, this is the result:
![image](https://github.com/axmolengine/axmol/assets/8603230/dd18bd71-9d45-4920-807c-ffbaa19b19fe)

It does go into the rounded corners on the right, which isn't optimal, but, it turns out that there is currently no way to determine if a device has rounded corners on Android.  The left side of that screenshot is inset correctly because of the cutout (where the camera is etc.).

https://stackoverflow.com/a/50205832/1664652
https://developer.android.com/develop/ui/views/layout/display-cutout

The suggestion is that you have a list of device names and adjust the sizing based on that, which you can do in your own project as you come across more devices with the issue.  

Alternatively, set a fixed cut-out size so it doesn't go all the way to the edge of the screen, regardless of what type of screen it is, assuming most screen released these days have rounded corners.  This is the method I personally use for getting around this issue.

This is not a bug in Axmol.

**Comment by crazyhappygame** [comment]
I used FIXED_WIDTH.
I think that safe area computation should be correct for all resolution policies.

Maybe we can use this:
https://developer.android.com/reference/android/view/WindowInsets#getRoundedCorner(int)

**Comment by rh101** [comment]
> I used FIXED_WIDTH. I think that safe area computation should be correct for all resolution policies.
> 
> Maybe we can use this: https://developer.android.com/reference/android/view/WindowInsets#getRoundedCorner(int)

This applies to API31 (Android12) or higher, and it's not as straightforward as it may seem.  An attempt to utilize this is in PR #1934, so try it out when you can, and let me know if it works for you.  I've tested all ResolutionPolicy types on it, and the safe area is correct on all when using the changes in that PR.
