### ISSUE TITLE
the templates should be part of the "internal" axmol folder for easier changes on it

### ISSUE THREAD

**Issue by aismann** [axmolengine/axmol#2190]
![image](https://github.com/user-attachments/assets/1a172878-be0e-40f4-99ae-20e7ea0afe44)

**Comment by rh101** [comment]
What do you mean by your post? It's not quite clear how the templates have anything to do with the virtual "internal" folder shown in the screenshot from Visual Studio.

**Comment by aismann** [comment]
The problem is:
At the moment its not possible to edit and test the templates directly on e.g.: Visual Studio.
e.g.: Here the cpp template as example:
axmol\templates\cpp\Source\ <files>

**Comment by rh101** [comment]
> At the moment its not possible to edit and test the templates directly on e.g.: Visual Studio.

I understand now.  

The issue though is that the new structure of the template folders means that they are no longer valid projects, isn't that right? If that is the case, then adding them to the Visual Studio solution will result in errors when attempting to build that solution, unless they can somehow be added as miscellaneous files etc..  Perhaps something like this:
```
file(GLOB_RECURSE AXMOL_TEMPLATE_FILES templates/*)
add_custom_target(ProjectTemplates SOURCES ${AXMOL_TEMPLATE_FILES})
set_target_properties(ProjectTemplates
    PROPERTIES
    FOLDER "Project Templates"
)
```

EDIT: I tried the above, and while it seems to add the files, they have a flat file structure, with the folders missing etc... so not very useful.  Maybe someone else knows how best to do this, assuming it is even possible.

**Comment by aismann** [comment]
> > At the moment its not possible to edit and test the templates directly on e.g.: Visual Studio.
>
> The issue though is that the new structure of the template folders means that they are no longer valid projects, isn't that right? 

A workaround is "Create a new project based on the 'templates' sources"
Edit it and copy the modified sources back to the template folder. 
And make the PR. => But this PR is not checked for  working on "all" platforms.

**Comment by rh101** [comment]
> A workaround is "Create a new project based on the 'templates' sources"
> Edit it and copy the modified sources back to the template folder.

The template isn't something that needs to be constantly updated, so I personally don't see that minor inconvenience as an issue.  

> And make the PR. => But this PR is not checked for working on "all" platforms.

With regards to the testing on all platforms, if platform-specific changes are being made, then that is not an issue, since they would be tested by the developer making the changes, so other platforms should never be affected.  

If changes are to be made to the common code in the template, then again I don't see how that would be a problem, because the common code should always be kept as simple as possible.  It is just a template after all, and if anything, the amount of code in it needs to be reduced rather than increased.  The template should not be showcasing what can be done with a project, but rather provide the minimal starting point.

If the purpose of any changes are to show an example of how a game is written, then that should be left to a different project altogether.

**Comment by aismann** [comment]
ok. I understand and close it
