### ISSUE TITLE
Localization Support

### ISSUE THREAD

**Issue by theunwisewolf** [axmolengine/axmol#775]
**Is your feature request related to a problem? Please describe.**
Games sometimes require localization support. Currently, UIText and CCLabel do not have any support for this.

**Describe the solution you'd like**
First, cocos-studio already has a localization manager that is unused (No support in cocos studio to enable localization, although it is part of the flatbuffer schema, see options->isLocalized()). I was thinking that maybe we can edit the reader code to localize strings if some global flag is set. Also, localization should be done in such a way that it also enables to set the font on the UIText, because some languages like arabic might require a different font. Maybe something like this:

```
// TextReader.cpp
ILocalizationManager* lm = LocalizationHelper::getCurrentManager();
if (lm) // or something like if (g_FlagEnableLocalization)
{
    lm->setLocalizedString(label, text);
}
else
{
    label->setString(text);
}

// CustomLocalizationManager.cpp
void CustomLocalizationManager::setLocalizedString(Text* node, std::string_view text)
{
      auto font = this->getFontBasedOnLanguage(_currentLanguage);
      node->setFontName(font);
      node->setString(this->localizeString(text));
}
```

**Describe alternatives you've considered**
Another alternative is to just mark UIText::setString() and UIText::setFontName() as virtual so users can write their custom UIText nodes inherited from UIText and then they can override setString() and setFontName().
The TextReader in cocos studio can already be overriden by registering the type in ObjectFactory before the app loads, and there instead of doing Text::create() we can create our custom TextCustom::create() node.

And, one more approach could be to just add localization support engine wide, so that setString() function localizes the text before it sets it.

Please suggest a good approach so I can work on it and submit a PR!

**Comment by DelinWorks** [comment]
I've elegantly written my own localization string and here is how it goes:

the `Label` or `Text` are inherited into a custom type called `LocalizedLabel` or `LocalizedText` and these classes that inherit the base just add one function, which is `setStringLocalized()` without passing an object reference or dealing with a singleton. one note `setStringLocalized()` can be added to the engine's code directly but I prefer not to modify the engine a lot as my changes could get a conflict. `setStringLocalized()` would go a localization manager singleton and check to look for a localized string in the files that have been loaded into that localization singleton, and if nothing is found (i.e file not loaded) then it would set the text to the same text as the localized key as to tell the developer that he/she forgot to load a localization file. also, the localization data could be loaded from JSON, plist, or XML files and for the font names it can be added as a second parameter or something.. that's the design I'd go for to minimize complexity!

**Comment by askamn** [comment]
That is fine, but the problem is with importing files from an editor, like
cocos studio or ax studio. We have to localize the strings while importing.

**Comment by DelinWorks** [comment]
you mean as in localise them we store them with a specific language?

**Comment by askamn** [comment]
No... Lets say you create a scene in CocosStudio/X-studio. You add a Text node to it with this string - "EN_SETTING_FPS" which a localization key. When loading it in axis with the cocostudio extension there is currently no way to localize this.
Ideally, while loading itself, there should be a way to get the localized value for this string ("EN_SETTING_FPS" => "Frames Per Second") and set it on the text node via ->setString(localizedString)
You can read the code in TextReader.cpp, you will understand. There is already a localization manager there, but the key isLocalized() is not supported and is always false.

**Comment by DelinWorks** [comment]
Oh! thanks for clearing that out I'll look into it!

**Comment by DelinWorks** [comment]
Can you send a code portion of creating and adding text using TextReaders because I didn't find any examples of it

**Comment by askamn** [comment]
Hi, 

You can do this -
Make a copy of TextReader.h and TextReader.cpp in your Classes/ folder somewhere. Rename the class to something else, e.g. `CustomTextReader`. Manually replace all the macros with their code, e.g. IMPLEMENT_CLASS_NODE_READER_INFO (This one is very important!) 

The IMPLEMENT_CLASS_NODE_READER_INFO macros defines the type info TInfo for a type, in our case TextReader. Now we want the type to remain the same, that is "TextReader" but we want it to be parsed by CustomTextReader. When you replace the macro, change the TInfo declaration to this - 
`axis::ObjectFactory::TInfo CustomTextReader::__Type("TextReader", &CustomTextReader::createInstance);`
Notice that in the string argument, I have used "TextReader". This is very important as this is the key of the reader that cocostudio uses to read UIText nodes.

Now the final step is to simply include your customtextreader file before any cocostudio files are included. This ensures that your type info will be registered first and when cocostudio textreader tries to register itself, it will fail because the map will already contain a key for "TextReader" (c++ maps do not allow duplicates, if a value exists, insertion is skipped).

If you still face issues, let me know and I will post my files.

**Comment by DelinWorks** [comment]
Wouldn't it be easier and more convenient if we just stick the localization to the `Label` class directly? it feels much more organized than this mess

**Comment by askamn** [comment]
That would be the best!

**Comment by DelinWorks** [comment]
`cocostudio` actually needs to be deprecated since it doesn't make sense and doesn't have documentation

**Comment by DelinWorks** [comment]
would this be a viable solution to loading a localization file from json?
of course, you have to organize localization in a way so that you load a file called `text_en.json` and it retrieves the english keys automatically, and the same goes for other languages but that's just an example.

```
{
    "english": [
      "some english text",
      "english_font.ttf"
    ],

    "arabic": [
      "نصوص عربية",
      "arabic_font.ttf"
    ]
}
```

**Comment by askamn** [comment]
I think a better solution would be to leave the localization file loading and string replacement to the game itself. The UIText / Label should just call the callbacks of whatever localization solution the game has implemented. For example, the label class could have a callback member variable -
```
// CCLabel.h
typedef std::string_view (*LocalizerCallback)(cocos2d::Label*, std::string_view);
LocalizerCallback _localizeString;

// CCLabel.cpp
void Label::setString(std::string_view text)
{
    if (_localizeString)
    {
        text = _localizeString(this, text);
    }

    if (text.compare(_utf8Text))
/// ... Other code
```

The advantage of this approach is that the game can then load its localization files any way it wants! Be it json, binary, xml, etc. And the same goes for replacement, it doesn't have to rely on any pattern imposed by the engine, like you said - "ENGLISH_KEY_1": "Health: %s" ... it can follow any pattern like "ENGLISH_KEY_1": "Health: {1}" or "ENGLISH_KEY_1": "Health: {%HEALTH%}", whatever. The engine doesn't care. All it does, is that is calls the code that handles this replacement.

**Comment by DelinWorks** [comment]
what about setting the font name and size? `LocalizerCallback` deals with it right?

**Comment by askamn** [comment]
Yeah, that's why the callback has the Label as the first parameter.

**Comment by DelinWorks** [comment]
Actually you can't have a callback as pointer.. it would pollute the class

**Comment by DelinWorks** [comment]
There you go

![image](https://user-images.githubusercontent.com/45469625/184150551-04b17e3d-e680-4a9b-a65b-e1bfc7fe40fd.png)

it got overwritten because my function only returns "WOW"

![image](https://user-images.githubusercontent.com/45469625/184150661-be825a73-45c3-4ef3-b180-de322cc20fb7.png)

now each time you set a label to that localizer it will hold on to it until it dies then it decreases the ref's count by 1, I called retain to make sure it stays with me even if all labels are destroyed, that's great memory management!

**Comment by aismann** [comment]
Maybe this is helping too?
![image](https://user-images.githubusercontent.com/8652787/194483056-36b2995f-71aa-4136-afe7-7cda20ff7e3f.png)

**Comment by aismann** [comment]
@theunwisewolf 
Is it still an issue?
What is miss?
