### ISSUE TITLE
Should we delete unaswered disscusion entries after some months?

### ISSUE THREAD

**Issue by aismann** [axmolengine/axmol#899]
Should we delete unaswered disscusion entries after some months?

like this one (I cant delete it and im the owner):
https://github.com/axmolengine/axmol/discussions/828

Maybe a magick word like "CloseMePlease" as last entry is the trigger for automatic deleting (only owner and admin can delete)?

**Comment by halx99** [comment]
The discussion not support auto delete, I can delete the discussion what you want

**Comment by aismann** [comment]
Ok. I will check later.

**Comment by rh101** [comment]
Is there a specific reason to delete the discussions? They may contain solutions to questions that others may want to ask, and since it's searchable, keeping them there may help others find the answers they want without asking the same questions again.

**Comment by aismann** [comment]
Deleting only unanswered entries. 
And of course only if it has checked 
IT was only an Idea.

**Comment by rh101** [comment]
Oh, I just wanted to know if there was a reason for asking for them to be deleted.  If there's no real reason, then there is no harm in leaving them there, even the unanswered questions, since they may still be important questions that we need to find an answer for. 

I can understand if pointless or silly posts are deleted, but any posts with information related to the engine usage may be helpful to users.

**Comment by aismann** [comment]
> 
> I can understand if pointless or silly posts are deleted, but any posts with information related to the engine usage may be helpful to users.

Of course that was my intention:  meaning pointless or silly posts.

**Comment by rh101** [comment]
> Of course that was my intention: meaning pointless or silly posts.

In that case, I totally agree with you.
