### ISSUE TITLE
Some RenderTexture issue

### ISSUE THREAD

**Issue by Yehsam23** [axmolengine/axmol#966]
- axmol version: newest
- devices test on: iOS 16
- developing environments
   - Xcode version: 14
   
Steps to Reproduce:
Sample Code:
[RenderTextureTest.zip](https://github.com/axmolengine/axmol/files/10054646/RenderTextureTest.zip)

1. add files to cpp_tests, and `Director::getInstance()->runWithScene(RenderTextureTest1::create());`
2. Touch and move, sometime screen will flick or disappear.
https://user-images.githubusercontent.com/1954445/202998155-69a98402-c81a-4f13-bbdb-7856b447c601.mov

 
Second issue:
1. click "Save", will crash
2. If switch to line 73 to 74, the file is empty

Third issue:
1. If uncomment line 103, it will not add any sprite

If i use cocos2dx is correct.

Sorry for my poor english.

**Comment by rh101** [comment]
Have you used a debugger to track down the source of the crash?  It would have led you to the fact that there are bugs in your own code.  Also, when you do debug, don't stop at your own code, but trace into the engine code to figure out what is going on in there.

Just a quick look at your code shows a problem right away; you are calling `retain()` on a local variable `newRT`, one which you're passing a callback to.  All sorts of bad things will happen as a result of that.  

```
void RenderTextureTest1::saveFile(Ref* pSender)
{
    auto director = Director::getInstance();
    auto s = director->getVisibleSize();
    auto newRT = RenderTexture::create(s.width, s.height, backend::PixelFormat::RGBA8, backend::PixelFormat::D24S8, false);
    
    newRT->beginWithClear(0, 0, 0, 0);

    // It's will crash on axmol, switch to _clippingNode will not show
    this->visit();
//    _clippingNode->Node::visit();

    newRT->end();
    
    auto callback = [&] (RenderTexture* rt, std::string_view path) {
        AXLOG("Save To Path=%s", path.data());
    };

    newRT->retain();
    newRT->saveToFile("TestSave.png", Image::Format::PNG, true, callback);

    // Add this function to avoid crash if we switch to a new scene.
    Director::getInstance()->getRenderer()->render();
}
```

The rendering command code used in Axmol is different to Cocos2d-x, so just because it works in Cocos2d-x doesn't mean that there is something wrong with Axmol.  What most likely happened to cause the crash is the fact that a callback command was added to the queue, as you can see in `RenderTexture::saveToFile`, and since the callback was passed using a local variable, by the time the callback was called, it had an invalid pointer.

**Comment by rh101** [comment]
@halx99 I just ran the standard test "43:Node: RenderTexture", and it's crashing on the first test if you move your touch the view area and move around.  It should draw items on the screen, but what seems to happen is that a few appear, then it starts flickering, like @Yehsam23 mentioned.  If you try to close the app, it crashes in `Renderer::~Renderer()` on this line:

```
    for (auto&& clearCommand : _callbackCommandsPool)
        delete clearCommand; <= here it crashes, and there are a lot of commands in the _callbackCommandsPool
```

It seems like once the number of commands in the _callbackCommandsPool go over a certain amount, it causes problems.

**Comment by rh101** [comment]
@halx99 Looking into this some more, I noticed that the `_callbackCommandsPool` contains copies of the same command pointers. The crash on exit happens because once one of those pointers is deleted in the loop, the rest become invalid, and since there are multiple entries of the same pointer, the delete fails:

![image](https://user-images.githubusercontent.com/8603230/203199958-59edccdc-8d91-47f6-b72b-45419801fa0c.png)
![image](https://user-images.githubusercontent.com/8603230/203200169-2cd1100c-3c50-4f0a-b1b0-0776aef1164e.png)

Aren't they supposed to only exist once in that vector?

**Comment by rh101** [comment]
So, a quick test using a lookup to check if the command already exists in the vector actually fixed the problem, but I still can't quite pinpoint why there is a problem to begin with.  It fixed both the drawing and the crash, and there were way less entries in the vector (like 9 commands vs 100's).

```
void Renderer::processRenderCommand(RenderCommand* command)
{
...

    case RenderCommand::Type::CUSTOM_COMMAND:
        flush();
        drawCustomCommand(command);
        break;
    case RenderCommand::Type::CALLBACK_COMMAND:
    {
        flush();
        static_cast<CallbackCommand*>(command)->execute();
        // Check if the pointer already exists before adding it to the vector
        auto&& itr = std::find(_callbackCommandsPool.begin(), _callbackCommandsPool.end(), command);
        if (itr == _callbackCommandsPool.end())
        {
            _callbackCommandsPool.emplace_back(static_cast<CallbackCommand*>(command));
        }
        break;
    }
    default:
        assert(false);
        break;
    }
}
```

**Comment by Yehsam23** [comment]
I found that it seems that this crash occurs when using two different RenderTextures

My above Second issue crash is here:
<img width="1096" alt="capture 2022-11-22 上午10 28 25" src="https://user-images.githubusercontent.com/1954445/203207092-1b285b4a-de9f-4ee4-9266-e6829c49f21e.png">
<img width="1070" alt="capture 2022-11-22 上午10 28 40" src="https://user-images.githubusercontent.com/1954445/203207155-8adb93ab-5074-41ca-ac15-0eed5426cfc7.png">
<img width="760" alt="capture 2022-11-22 上午10 34 26" src="https://user-images.githubusercontent.com/1954445/203207171-f73734e0-d7e1-4cb4-ae4e-96de0e4fb111.png">

**Comment by rh101** [comment]
@Yehsam23 It's hard to tell why yours is crashing with the save without the exact code you're using.  I mentioned in my previous post that the initial code you post is incorrect, specifically in the `RenderTextureTest1::saveFile` method.  Did you fix the issue in that function? Is the crash you're seeing now based on the original or fixed code?

**Comment by Yehsam23** [comment]
@rh101
I know i need to release, It just quick sample test for crash,  and I don't need `newRT` pointer to do anything
I just want to say saveToFile will crash if use that code. 

```
    case RenderCommand::Type::CALLBACK_COMMAND:
    {
        flush();
        static_cast<CallbackCommand*>(command)->execute();
        // Check if the pointer already exists before adding it to the vector
        auto&& itr = std::find(_callbackCommandsPool.begin(), _callbackCommandsPool.end(), command);
        if (itr == _callbackCommandsPool.end())
        {
            _callbackCommandsPool.emplace_back(static_cast<CallbackCommand*>(command));
        }
        break;
    }
```
It will stop crash
But if you press SaveToFile for the second time, the screenshot file will incorrect (Different from the screen)
If remove `Director::getInstance()->getRenderer()->render();` , it will be correct

So what I want to determine is whether it is not suitable to use Director::getInstance()->getRenderer()->render() under axmol?
Just like the third question I mentioned above, the two screens will be different
Currently only happens on iOS

**Comment by rh101** [comment]
In case this helps:

`_renderGroups` seems to have multiple entries for renderQueueID = 1, which is the one that contains the callback commands:
![image](https://user-images.githubusercontent.com/8603230/203213796-a93d57ec-e22a-42ea-89a7-f5bd0ac130e4.png)

Now, when it loops through, it is processing the same group multiple times, and since the group contains the exact same callback command pointers, it attempts to add them multiple times to the `_callbackCommandsPool` once they're processed:
![image](https://user-images.githubusercontent.com/8603230/203214188-aa282c32-ee30-4853-9872-7ced99f24e4a.png)
![image](https://user-images.githubusercontent.com/8603230/203214616-efeeaa4f-101f-49f3-a23c-a002c63b8102.png)

EMPLACE: 0BADDA78
POP: 0BADDA78
EMPLACE: 0BADDA78
POP: 0BADDA78
EMPLACE: 0BADDA78
POP: 0BADDA78
POP: 0BADF2F0
POP: 0BADE720
EMPLACE: 0BADE720
EMPLACE: 0BADDA78
EMPLACE: 0BADF2F0
POP: 0BADF2F0
POP: 0BADDA78
POP: 0BADE720
POP: 0BADE138
NEW: 0BADE210
NEW: 0BADD8C8
NEW: 0BADDF88
EMPLACE: 0BADDF88
EMPLACE: 0BADF2F0
EMPLACE: 0BADDA78
EMPLACE: 0BADE720
EMPLACE: 0BADE138
EMPLACE: 0BADE210
EMPLACE: 0BADD8C8
DUPLICATE EMPLACE: 0BADF2F0
DUPLICATE EMPLACE: 0BADDA78
DUPLICATE EMPLACE: 0BADE720
DUPLICATE EMPLACE: 0BADE138
DUPLICATE EMPLACE: 0BADE210
DUPLICATE EMPLACE: 0BADD8C8
DUPLICATE EMPLACE: 0BADF2F0
DUPLICATE EMPLACE: 0BADDA78
DUPLICATE EMPLACE: 0BADE720
DUPLICATE EMPLACE: 0BADE138
DUPLICATE EMPLACE: 0BADE210
DUPLICATE EMPLACE: 0BADD8C8

**Comment by rh101** [comment]
All of the problems start when `RenderTexture::begin()` is called, which is when it uses the exact same group, resulting in multiple entries in the rendering queue:

```
void RenderTexture::begin()
{
...
    Renderer* renderer = _director->getRenderer();
    renderer->addCommand(&_groupCommand);
    renderer->pushGroup(_groupCommand.getRenderQueueID());
...
}
```

**Comment by rh101** [comment]
As far as I can tell, if `RenderTexture::begin()` is called more than once per render cycle for the same instance of `RenderTexture`, then it ends up adding multiple entries in the render queue for the same `renderQueueID`.  That causes the group to be processed more than once, and results in the `Renderer::processRenderCommand` processing the same commands again and also adds the commands back into the `_callbackCommandsPool`, even though they already exist in there.

**Comment by aismann** [comment]
Maybe a look into the history of CCRender.cpp is useful too?
In an earlier version (axis) it was working.

**Comment by rh101** [comment]
> Find the last "working" version and check what is changed on the version after.

Yeah the render code was changed significantly, with additions such as the `_callbackCommandsPool` etc.  My previous post with the changes to `RenderQueue::emplace_back(RenderCommand* command)` does fix all the issues, but again, I'm not certain that it is the correct way to fix it.

**Comment by aismann** [comment]
@rh101 
Maybe your fix can used add a workaround?

@halx99 
This issue should be pinned.
Workaround should be merged.
And a deepher look until and after release of axmol 1.0.

**Comment by rh101** [comment]
@halx99 I'll submit a PR for this with the GroupCommand pooling similar to how the CallbackCommand pooling is handled, but it's completely up to you to decide if it is a reasonable way to fix these issues. This change means there is no need to do iterate through the pooled data to check if a reference to the command already exists in there, so there should be no impact whatsoever on performance.

This change is based on my understanding of how things seem to work, but it's not an area I am 100% familiar with, so it may not be the best way to fix the underlying issues.

**Comment by aismann** [comment]
@rh101 
Small question:
Make this PR the render process also faster (at least for class RenderTexture)?
If yes it makes sense to add this PR.
My point of view.

**Comment by Yehsam23** [comment]
I merge pr #969 , it's has fixed most of the issues
But iOS have same issue in `Director::getInstance()->getRenderer()->render();`
It can be reproduce by "40:Node: RenderTexture" 
at `RenderTextureSave::addImage` add `Director::getInstance()->getRenderer()->render();` to the last line
iOS can't show any image if clicked "Add Image"

**Comment by Yehsam23** [comment]
What I want to express is that using `Director::getInstance()->getRenderer()->render();` under iOS will make RenderTexture useless

That's why I said that the way to reproduce is as above

**Comment by rh101** [comment]
> What I want to express is that using `Director::getInstance()->getRenderer()->render();` under iOS will make RenderTexture useless
> 
> That's why I said that the way to reproduce is as above

Please don't make changes to code and report issues in this manner.  If you want to show an issue, then create a new project with the minimal amount of code required to reproduce the problem, then post that code either here or in a github repo for others to download and test.

**Comment by Yehsam23** [comment]
OK, this is a sample project
[TestRenderTexture.zip](https://github.com/axmolengine/axmol/files/10088161/TestRenderTexture.zip)

It is work on Android, but there will be problems on iOS

I have tried to find the problem, that part seems to be related to Metal, I can't figure out how to start

**Comment by solan-solan** [comment]
About groupCommand and RenderTerxture. 
If I properly understand? The issue due to the fact that _groupCommand can be added to the render queue multiple times in a frame? It is more like on bad implementation of RenderTexture class, do not you think so?

I did test and this fix should help with cpp_test (bode 43 ex.)

![image](https://user-images.githubusercontent.com/73186496/203973708-4dcc0c75-6f6a-45a5-934c-f8d40135b61f.png)
![image](https://user-images.githubusercontent.com/73186496/203973958-7dd9e082-7cf1-431f-95ca-2ebfaac2b7aa.png)
![image](https://user-images.githubusercontent.com/73186496/203974010-d39973b3-02f8-4261-a994-a3f153244238.png)

If I understand @rh101 propose the same thing, to use  separate instance of _groupCommand for each RenderTexture::begin() calling, or I wrong?

**Comment by rh101** [comment]
@solan-solan I'll test it with your change to see if it fixes the issues I was seeing, and if it does work, then yours will be a simpler fix.

**Comment by solan-solan** [comment]
@rh101 I checked your decision one more time, and looks like it is good idea anyway to have separate pool for group commands. It is more general aproach and it does not touch render cycle. Since that I would say it is more good solution.

**Comment by rh101** [comment]
@solan-solan With the changes you suggested to RenderTexture, how do you reset the `_is_set_group` before the next render cycle, because it does need to be reset once that render cycle is complete.

**Comment by solan-solan** [comment]
@rh101 To my understand _RenderTexture::begin()_ is called from the _event handler_ and it could be called multiple times in a frame by the reason. But _RenderTexture::onBegin()_ is called from the render cycle when _events_ are not processed already. And it is good place to reset _is_set_group before next frame in my changes

**Comment by rh101** [comment]
> But _RenderTexture::onBegin()_ is called from the render cycle when _events_ are not processed already.

I see what you mean, and there is also `RenderTexture::onEnd()`, which may be more suitable too, since that will definitely the end of processing the render group for that render texture.

**Comment by aismann** [comment]
@solan-solan 
I tested your fix.  (` _is_set_group  = false;` ....) 
Works well on windows 2022 64bit

**Comment by rh101** [comment]
@solan-solan I tested it with the original code (in the first post), and it works with the cpp_tests, but it still crashes when calling `RenderTexture::saveToFile(...)` more than once in the code that Yehsam23 posted (first post). 

If you run that code, click the "Save" button, wait for it to save the image, then click it again, and the graphics become distorted, then click it again two more times, and it starts flickering, and then if you close the application, the application crashes on exit with the same issue as before, duplicate CallbackCommand entries in the list render list.  The only way to avoid the graphic glitches and longer crash is to add a "Director::getInstance()->getRenderer()->render();" to the end of the call.

```
void HelloWorld::saveFile(Ref* pSender)
{
    auto director = Director::getInstance();
    auto s = director->getVisibleSize();
    if (!newRT)
    {
        newRT = RenderTexture::create(s.width, s.height, backend::PixelFormat::RGBA8, backend::PixelFormat::D24S8, false);
        newRT->retain();
    }

    newRT->beginWithClear(0, 0, 0, 0);
    this->visit();
    newRT->end();

    auto callback = [&](RenderTexture* rt, std::string_view path) {
        AXLOG("Save To Path=%s", path.data());
    };

    newRT->saveToFile("TestSave.png", Image::Format::PNG, true, callback);

    // Add this function to avoid crash on exit or scene switch
    Director::getInstance()->getRenderer()->render();
}
```

So, if that last line is removed, the graphic glitches and a crash on exit occurs.

**Comment by solan-solan** [comment]
[RenderTextureTest.zip](https://github.com/axmolengine/axmol/files/10095191/RenderTextureTest.zip)

Added this test to the original RenderTest, you can replace it with original files (it is first now).
There is no error if
![image](https://user-images.githubusercontent.com/73186496/204058940-64ee61ab-e80b-4d35-a232-ca0dd5a60277.png)
Of couse there is no some data in the  saved file. Now it is clear that after commented _visit_ some render commads are broken when 'save' button is pressend _second_ time.

**Comment by rh101** [comment]
> Now it is clear that if uncommented _visit_ some render commads are broken when 'save' button is pressend _second_ time.

Yes, it seems so.  The only way I've managed to get it all completely working is with the group command pool implementation, which avoids having to do any checks in RenderTexture and anywhere else that may require more than one render command in the queue per render cycle.

**Comment by solan-solan** [comment]
@rh101 I have nothing against your decision, but - does your soltion require this line for properly usage?
```
// Add this function to avoid crash on exit or scene switch
    Director::getInstance()->getRenderer()->render();
```

I believe it is needed more investigations if so.

----
 The issue occured if the lines to save to file are commented in the code I attached. It is not related with saving to file
![image](https://user-images.githubusercontent.com/73186496/204086252-67e36139-7252-47d2-9b40-4787040cafef.png)


There is no issue in this code
```
_rt->begin();

    _iconSprite->setVisible(true);
    _iconSprite->setPosition(touchPos);
    _iconSprite->visit();
    _iconSprite->setVisible(false);

    _rt->end();
```

But error happens there
```
 newRT->beginWithClear(0, 0, 0, 0);

    // It's will crash on axmol, switch to _clippingNode will not show
    this->visit();
    //    _clippingNode->Node::visit();

    newRT->end();
```

There should be some difference in the rendered nodes.

**Comment by rh101** [comment]
> @rh101 I have nothing against your decision, but - does your soltion require this line for properly usage?
> 
> ```
> // Add this function to avoid crash on exit or scene switch
>     Director::getInstance()->getRenderer()->render();
> ```

The GroupCommand pool implementation works both with or without the line `Director::getInstance()->getRenderer()->render();` in that code.  

> The issue occured if the lines to save to file are commented in the code I attached. It is not related with saving to file

That's very interesting, and it's something I didn't think of checking. Good catch!




> But error happens there
> 
> ```
>  newRT->beginWithClear(0, 0, 0, 0);
> 
>     // It's will crash on axmol, switch to _clippingNode will not show
>     this->visit();
>     //    _clippingNode->Node::visit();
> 
>     newRT->end();
> ```
> 
> There should be some difference in the rendered nodes.

Yes, that would explain the duplicate Stencil-related callbacks that were causing the crashes.  Perhaps it's something in the stencil clipping code that is causing the issue.

**Comment by solan-solan** [comment]
@rh101 
`The GroupCommand pool implementation works both with or without the line Director::getInstance()->getRenderer()->render(); in that code.`
This line is overhead, and it is good that it is not necessary.

I noticed that you fixed ClippingNode also, about group commands? Looks like these group commands are added to the render queue twice per render cycle. First one, by ther reason of the _clippingNode is the child of scene, and the second one by the reason of _this->visit()_ inside _RenderTextureTest1::saveFile(Ref* pSender)_.
If that, your solution should be integrated since it is needed to have two different instances of those group commands anyway.

**Comment by rh101** [comment]
> I noticed that you fixed ClippingNode also, about group commands?

Yes, the group command pooling fixed all of those issues.  The only one remaining that @Yehsam23 mentioned has to do with iOS/Metal renderer, so not sure what is going on with that platform.

> Looks like these group commands are added to the render queue twice per render cycle. First one, by ther reason of the _clippingNode is the child of scene, and the second one by the reason of _this->visit()_ inside _RenderTextureTest1::saveFile(Ref* pSender)_.

Oh, well that makes sense then why there were multiple instances of the commands in the CallbackCommand pool, and it was crashing because it would try to call "delete" on the same CallbackCommand pointers more than once when iterating through them.

> If that, your solution should be integrated since it is needed to have two different instances of those group commands anyway.

That is how it works, so regardless of how many group commands are required from any code within the same render cycle, it will always be a unique one in the queue, which is how the issues were fixed.

**Comment by solan-solan** [comment]
> The only one remaining that @Yehsam23 mentioned has to do with iOS/Metal renderer, so not sure what is going on with that platform.

@rh101
I do not use this platform now, but it would be better to check if render to texture works at all somehow there, without ClippingNode. Only try to render to texture some simple sprite like _iconSprite, without saving to file, then if it does not cause to crash, try to save it. May be it is issue of metal created frame buffer or render texture for this buffer.

@Yehsam23
It is not clear if "group command pool fix" does not effect ios at all? Or may be something become different?

**Comment by Yehsam23** [comment]
"Group command pool fix" fixed the issue that iOS and Android would flick or disappear.

Another iOS/Metal issue I guess need to call `_renderer->beginFrame();` before `Director::getInstance()->getRenderer()->render()` and call `_renderer->endFrame();` at end

Maybe i close this issue first, and handle the iOS issue separately?

**Comment by Yehsam23** [comment]
#969 Fixed issue

**Comment by Yehsam23** [comment]
#969 Fixed Issue
